export const images = {
  hero: {
    blackfriday: "/Images/hero/hero-blackfriday.webp",
    noel: "/Images/hero/hero-noel.webp",
    nouvelan: "/Images/hero/hero-nouvelan.webp",
  },
  categories: {
    femme: "/Images/Cat%C3%A9gories/femme.webp",
    homme: "/Images/Cat%C3%A9gories/homme.webp",
    accessoires: "/Images/Cat%C3%A9gories/accessoires.webp",
    promos: "/Images/Cat%C3%A9gories/promos.webp",
  },
  products: {
    placeholder: "/Images/Produits/blazer-oversize-nova-1.webp",
    nova: "/Images/Produits/blazer-oversize-nova-1.webp",
    novaAlt: "/Images/Produits/blazer-oversize-nova-2.webp",
    urban: "/Images/Produits/bomber-urban-ivoire-1.webp",
    urbanAlt: "/Images/Produits/bomber-urban-ivoire-2.webp",
    atlas: "/Images/Produits/pantalon-wide-leg-atlas-1.webp",
    atlasAlt: "/Images/Produits/pantalon-wide-leg-atlas-2.webp",
    lune: "/Images/Produits/crop-top-lune-1.webp",
    luneAlt: "/Images/Produits/crop-top-lune-2.webp",
    dakar: "/Images/Produits/jean-relaxed-dakar-1.webp",
    dakarAlt: "/Images/Produits/jean-relaxed-dakar-2.webp",
    zero: "/Images/Produits/veste-utilitaire-zero-1.webp",
    zeroAlt: "/Images/Produits/veste-utilitaire-zero-2.webp",
    ayo: "/Images/Produits/sac-structure-ayo-1.webp",
    ayoAlt: "/Images/Produits/sac-structure-ayo-2.webp",
    sneakers: "/Images/Produits/sneakers-blanc-studio-1.webp",
    sneakersAlt: "/Images/Produits/sneakers-blanc-studio-2.webp",
  },
  focus: {
    flashOffer: "50% 8%",
    hero: {
      blackfriday: "50% 15%",
      noel: "50% 15%",
      nouvelan: "50% 15%",
    },
    categories: {
      femme: "50% 12%",
      homme: "50% 12%",
      accessoires: "50% 50%",
      promos: "50% 12%",
    },
    products: {
      "nova-blazer": "50% 10%",
      "urban-bomber": "50% 10%",
      "atlas-wide-leg": "50% 10%",
      "lune-crop-top": "50% 10%",
      "dakar-relaxed-jean": "50% 10%",
      "zero-utility-jacket": "50% 10%",
      "ayo-structured-bag": "50% 50%",
      "blanc-studio-sneakers": "50% 50%",
    },
  },
} as const;