import type { Product } from "@/core/types";
import { images } from "@/brands/mode/images";

export const products: Product[] = [
	{
		id: "nova-blazer",
		slug: "blazer-oversize-nova",
		name: "Blazer oversize Nova",
		category: "Femme",
		gender: "femme",
		subcategory: "Vestes",
		price: 38000,
		images: [images.products.nova, images.products.novaAlt],
		sizes: ["S", "M", "L", "XL"],
		colors: [{ name: "Noir", hex: "#171A1F" }, { name: "Sable", hex: "#D9CCB6" }],
		stock: 7,
		tags: ["new", "bestseller"],
		rating: 4.8,
		createdAt: "2026-09-21T10:00:00.000Z",
		popularity: 96,
		description: "Une coupe ample et structurée, pensée pour composer une silhouette contemporaine.",
	},
	{
		id: "urban-bomber",
		slug: "bomber-urban-ivoire",
		name: "Bomber Urban Ivoire",
		category: "Mixte",
		gender: "mixte",
		subcategory: "Vestes",
		price: 32000,
		oldPrice: 40000,
		images: [images.products.urban, images.products.urbanAlt],
		sizes: ["S", "M", "L", "XL"],
		colors: [{ name: "Ivoire", hex: "#F1ECE1" }, { name: "Olive", hex: "#68745A" }],
		stock: 12,
		tags: ["promo", "bestseller"],
		rating: 4.7,
		createdAt: "2026-08-15T10:00:00.000Z",
		popularity: 100,
		description: "Un bomber léger aux lignes nettes, facile à superposer au quotidien.",
	},
	{
		id: "atlas-wide-leg",
		slug: "pantalon-wide-leg-atlas",
		name: "Pantalon wide-leg Atlas",
		category: "Femme",
		gender: "femme",
		subcategory: "Pantalons",
		price: 24000,
		images: [images.products.atlas, images.products.atlasAlt],
		sizes: ["XS", "S", "M", "L"],
		colors: [{ name: "Noir", hex: "#171A1F" }, { name: "Écru", hex: "#E8E1D4" }],
		stock: 9,
		tags: ["new"],
		rating: 4.6,
		createdAt: "2026-08-25T10:00:00.000Z",
		popularity: 83,
		description: "Une jambe ample et un tombé fluide pour une allure décontractée et précise.",
	},
	{
		id: "lune-crop-top",
		slug: "crop-top-lune",
		name: "Crop top Lune",
		category: "Femme",
		gender: "femme",
		subcategory: "Hauts",
		price: 12000,
		images: [images.products.lune, images.products.luneAlt],
		sizes: ["XS", "S", "M", "L"],
		colors: [{ name: "Blanc", hex: "#F8F7F3" }, { name: "Noir", hex: "#171A1F" }, { name: "Bordeaux", hex: "#6D293C" }],
		stock: 3,
		tags: ["new"],
		rating: 4.5,
		createdAt: "2026-09-26T10:00:00.000Z",
		popularity: 71,
		description: "Un essentiel à la coupe courte, aux finitions sobres et faciles à associer.",
	},
	{
		id: "dakar-relaxed-jean",
		slug: "jean-relaxed-dakar",
		name: "Jean relaxed Dakar",
		category: "Homme",
		gender: "homme",
		subcategory: "Jeans",
		price: 26000,
		oldPrice: 32000,
		images: [images.products.dakar, images.products.dakarAlt],
		sizes: ["S", "M", "L", "XL", "XXL"],
		colors: [{ name: "Bleu brut", hex: "#314965" }, { name: "Délavé", hex: "#74859B" }],
		stock: 14,
		tags: ["promo", "bestseller"],
		rating: 4.9,
		createdAt: "2026-08-12T10:00:00.000Z",
		popularity: 98,
		description: "Un denim relaxed au volume équilibré, confortable du matin au soir.",
	},
	{
		id: "zero-utility-jacket",
		slug: "veste-utilitaire-zero",
		name: "Veste utilitaire Zéro",
		category: "Homme",
		gender: "homme",
		subcategory: "Vestes",
		price: 34000,
		images: [images.products.zero, images.products.zeroAlt],
		sizes: ["S", "M", "L", "XL"],
		colors: [{ name: "Olive", hex: "#68745A" }, { name: "Noir", hex: "#171A1F" }],
		stock: 6,
		tags: ["new"],
		rating: 4.4,
		createdAt: "2026-09-18T10:00:00.000Z",
		popularity: 77,
		description: "Une veste fonctionnelle aux détails discrets et à la silhouette moderne.",
	},
	{
		id: "ayo-structured-bag",
		slug: "sac-structure-ayo",
		name: "Sac structuré Ayo",
		category: "Accessoires",
		gender: "mixte",
		subcategory: "Sacs",
		price: 29000,
		oldPrice: 35000,
		images: [images.products.ayo, images.products.ayoAlt],
		sizes: ["Unique"],
		colors: [{ name: "Noir", hex: "#171A1F" }, { name: "Cognac", hex: "#A96C42" }],
		stock: 4,
		tags: ["promo", "bestseller"],
		rating: 4.8,
		createdAt: "2026-08-10T10:00:00.000Z",
		popularity: 92,
		description: "Un format structuré et pratique, relevé par des lignes minimalistes.",
	},
	{
		id: "blanc-studio-sneakers",
		slug: "sneakers-blanc-studio",
		name: "Sneakers Blanc Studio",
		category: "Accessoires",
		gender: "mixte",
		subcategory: "Chaussures",
		price: 27000,
		images: [images.products.sneakers, images.products.sneakersAlt],
		sizes: ["38", "39", "40", "41", "42", "43", "44"],
		colors: [{ name: "Blanc", hex: "#F8F7F3" }, { name: "Blanc / Vert", hex: "#0B8A5F" }],
		stock: 8,
		tags: ["new", "bestseller"],
		rating: 4.7,
		createdAt: "2026-08-14T10:00:00.000Z",
		popularity: 89,
		description: "Des sneakers épurées pensées pour accompagner les silhouettes de tous les jours.",
	},
];

export function getProductBySlug(slug: string): Product | undefined {
	return products.find((product) => product.slug === slug);
}